/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export interface QuantumPrivacyComputeInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "MAX_QUBITS"
      | "authorizeNode"
      | "authorizedNodes"
      | "compileQuantumCircuit"
      | "computeJobCounter"
      | "computeJobs"
      | "createEntanglement"
      | "emergencyPause"
      | "executeQuantumAlgorithm"
      | "getCircuitInfo"
      | "getJobInfo"
      | "getJobResult"
      | "getPauserCount"
      | "getQuantumStateInfo"
      | "getUserJobHistory"
      | "initializeQuantumState"
      | "isDecryptionAllowed"
      | "isSindCpadEnabled"
      | "jobDecryptionCallback"
      | "owner"
      | "protocolId"
      | "quantumCircuits"
      | "requestJobDecryption"
      | "revokeNodeAuthorization"
      | "submitQuantumJob"
      | "updateMaxQubits"
      | "userJobHistory"
      | "verifyQuantumResult"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "CircuitCompiled"
      | "EntanglementCreated"
      | "NodeAuthorized"
      | "QuantumJobCompleted"
      | "QuantumJobSubmitted"
      | "QuantumResultDecrypted"
      | "QuantumStateInitialized"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "MAX_QUBITS",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "authorizeNode",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "authorizedNodes",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "compileQuantumCircuit",
    values: [BigNumberish, BigNumberish[], BigNumberish[], BigNumberish[]]
  ): string;
  encodeFunctionData(
    functionFragment: "computeJobCounter",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "computeJobs",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "createEntanglement",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "emergencyPause",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "executeQuantumAlgorithm",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getCircuitInfo",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getJobInfo",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getJobResult",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getPauserCount",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getQuantumStateInfo",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getUserJobHistory",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "initializeQuantumState",
    values: [BigNumberish[], BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "isDecryptionAllowed",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "isSindCpadEnabled",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "jobDecryptionCallback",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "protocolId",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "quantumCircuits",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "requestJobDecryption",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "revokeNodeAuthorization",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "submitQuantumJob",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "updateMaxQubits",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "userJobHistory",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "verifyQuantumResult",
    values: [BigNumberish, BigNumberish]
  ): string;

  decodeFunctionResult(functionFragment: "MAX_QUBITS", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "authorizeNode",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "authorizedNodes",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "compileQuantumCircuit",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "computeJobCounter",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "computeJobs",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "createEntanglement",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "emergencyPause",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "executeQuantumAlgorithm",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getCircuitInfo",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "getJobInfo", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getJobResult",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getPauserCount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getQuantumStateInfo",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getUserJobHistory",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "initializeQuantumState",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "isDecryptionAllowed",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "isSindCpadEnabled",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "jobDecryptionCallback",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "protocolId", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "quantumCircuits",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "requestJobDecryption",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "revokeNodeAuthorization",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "submitQuantumJob",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "updateMaxQubits",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "userJobHistory",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "verifyQuantumResult",
    data: BytesLike
  ): Result;
}

export namespace CircuitCompiledEvent {
  export type InputTuple = [circuitId: BigNumberish, depth: BigNumberish];
  export type OutputTuple = [circuitId: bigint, depth: bigint];
  export interface OutputObject {
    circuitId: bigint;
    depth: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace EntanglementCreatedEvent {
  export type InputTuple = [user1: AddressLike, user2: AddressLike];
  export type OutputTuple = [user1: string, user2: string];
  export interface OutputObject {
    user1: string;
    user2: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace NodeAuthorizedEvent {
  export type InputTuple = [node: AddressLike];
  export type OutputTuple = [node: string];
  export interface OutputObject {
    node: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace QuantumJobCompletedEvent {
  export type InputTuple = [jobId: BigNumberish, submitter: AddressLike];
  export type OutputTuple = [jobId: bigint, submitter: string];
  export interface OutputObject {
    jobId: bigint;
    submitter: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace QuantumJobSubmittedEvent {
  export type InputTuple = [
    jobId: BigNumberish,
    submitter: AddressLike,
    algorithmType: BigNumberish
  ];
  export type OutputTuple = [
    jobId: bigint,
    submitter: string,
    algorithmType: bigint
  ];
  export interface OutputObject {
    jobId: bigint;
    submitter: string;
    algorithmType: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace QuantumResultDecryptedEvent {
  export type InputTuple = [
    requestId: BigNumberish,
    decryptedValue: BigNumberish
  ];
  export type OutputTuple = [requestId: bigint, decryptedValue: bigint];
  export interface OutputObject {
    requestId: bigint;
    decryptedValue: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace QuantumStateInitializedEvent {
  export type InputTuple = [user: AddressLike, qubitCount: BigNumberish];
  export type OutputTuple = [user: string, qubitCount: bigint];
  export interface OutputObject {
    user: string;
    qubitCount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface QuantumPrivacyCompute extends BaseContract {
  connect(runner?: ContractRunner | null): QuantumPrivacyCompute;
  waitForDeployment(): Promise<this>;

  interface: QuantumPrivacyComputeInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  MAX_QUBITS: TypedContractMethod<[], [bigint], "view">;

  authorizeNode: TypedContractMethod<
    [_node: AddressLike],
    [void],
    "nonpayable"
  >;

  authorizedNodes: TypedContractMethod<[arg0: AddressLike], [boolean], "view">;

  compileQuantumCircuit: TypedContractMethod<
    [
      _circuitId: BigNumberish,
      _gateTypes: BigNumberish[],
      _targetQubits: BigNumberish[],
      _controlQubits: BigNumberish[]
    ],
    [void],
    "nonpayable"
  >;

  computeJobCounter: TypedContractMethod<[], [bigint], "view">;

  computeJobs: TypedContractMethod<
    [arg0: BigNumberish],
    [
      [
        string,
        string,
        string,
        bigint,
        boolean,
        boolean,
        bigint,
        bigint,
        bigint
      ] & {
        submitter: string;
        encryptedInput: string;
        encryptedResult: string;
        algorithmType: bigint;
        isCompleted: boolean;
        isVerified: boolean;
        submitTime: bigint;
        completeTime: bigint;
        gasUsed: bigint;
      }
    ],
    "view"
  >;

  createEntanglement: TypedContractMethod<
    [_partner: AddressLike],
    [void],
    "nonpayable"
  >;

  emergencyPause: TypedContractMethod<[], [void], "nonpayable">;

  executeQuantumAlgorithm: TypedContractMethod<
    [_jobId: BigNumberish],
    [void],
    "nonpayable"
  >;

  getCircuitInfo: TypedContractMethod<
    [_circuitId: BigNumberish],
    [
      [bigint[], bigint[], boolean, bigint] & {
        gateTypes: bigint[];
        targetQubits: bigint[];
        isCompiled: boolean;
        depth: bigint;
      }
    ],
    "view"
  >;

  getJobInfo: TypedContractMethod<
    [_jobId: BigNumberish],
    [
      [string, bigint, boolean, boolean, bigint, bigint, bigint] & {
        submitter: string;
        algorithmType: bigint;
        isCompleted: boolean;
        isVerified: boolean;
        submitTime: bigint;
        completeTime: bigint;
        gasUsed: bigint;
      }
    ],
    "view"
  >;

  getJobResult: TypedContractMethod<[_jobId: BigNumberish], [string], "view">;

  getPauserCount: TypedContractMethod<[], [bigint], "view">;

  getQuantumStateInfo: TypedContractMethod<
    [_user: AddressLike],
    [
      [bigint, boolean, bigint] & {
        qubitCount: bigint;
        isEntangled: boolean;
        timestamp: bigint;
      }
    ],
    "view"
  >;

  getUserJobHistory: TypedContractMethod<
    [_user: AddressLike],
    [bigint[]],
    "view"
  >;

  initializeQuantumState: TypedContractMethod<
    [_amplitudes: BigNumberish[], _qubitCount: BigNumberish],
    [void],
    "nonpayable"
  >;

  isDecryptionAllowed: TypedContractMethod<[], [boolean], "view">;

  isSindCpadEnabled: TypedContractMethod<[], [boolean], "view">;

  jobDecryptionCallback: TypedContractMethod<
    [requestId: BigNumberish, decryptedValue: BigNumberish],
    [bigint],
    "nonpayable"
  >;

  owner: TypedContractMethod<[], [string], "view">;

  protocolId: TypedContractMethod<[], [bigint], "view">;

  quantumCircuits: TypedContractMethod<
    [arg0: BigNumberish],
    [[boolean, bigint] & { isCompiled: boolean; depth: bigint }],
    "view"
  >;

  requestJobDecryption: TypedContractMethod<
    [_jobId: BigNumberish],
    [bigint],
    "nonpayable"
  >;

  revokeNodeAuthorization: TypedContractMethod<
    [_node: AddressLike],
    [void],
    "nonpayable"
  >;

  submitQuantumJob: TypedContractMethod<
    [_encryptedInput: BigNumberish, _algorithmType: BigNumberish],
    [bigint],
    "nonpayable"
  >;

  updateMaxQubits: TypedContractMethod<
    [_newMax: BigNumberish],
    [void],
    "nonpayable"
  >;

  userJobHistory: TypedContractMethod<
    [arg0: AddressLike, arg1: BigNumberish],
    [bigint],
    "view"
  >;

  verifyQuantumResult: TypedContractMethod<
    [_jobId: BigNumberish, _expectedResult: BigNumberish],
    [boolean],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "MAX_QUBITS"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "authorizeNode"
  ): TypedContractMethod<[_node: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "authorizedNodes"
  ): TypedContractMethod<[arg0: AddressLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "compileQuantumCircuit"
  ): TypedContractMethod<
    [
      _circuitId: BigNumberish,
      _gateTypes: BigNumberish[],
      _targetQubits: BigNumberish[],
      _controlQubits: BigNumberish[]
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "computeJobCounter"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "computeJobs"
  ): TypedContractMethod<
    [arg0: BigNumberish],
    [
      [
        string,
        string,
        string,
        bigint,
        boolean,
        boolean,
        bigint,
        bigint,
        bigint
      ] & {
        submitter: string;
        encryptedInput: string;
        encryptedResult: string;
        algorithmType: bigint;
        isCompleted: boolean;
        isVerified: boolean;
        submitTime: bigint;
        completeTime: bigint;
        gasUsed: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "createEntanglement"
  ): TypedContractMethod<[_partner: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "emergencyPause"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "executeQuantumAlgorithm"
  ): TypedContractMethod<[_jobId: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "getCircuitInfo"
  ): TypedContractMethod<
    [_circuitId: BigNumberish],
    [
      [bigint[], bigint[], boolean, bigint] & {
        gateTypes: bigint[];
        targetQubits: bigint[];
        isCompiled: boolean;
        depth: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "getJobInfo"
  ): TypedContractMethod<
    [_jobId: BigNumberish],
    [
      [string, bigint, boolean, boolean, bigint, bigint, bigint] & {
        submitter: string;
        algorithmType: bigint;
        isCompleted: boolean;
        isVerified: boolean;
        submitTime: bigint;
        completeTime: bigint;
        gasUsed: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "getJobResult"
  ): TypedContractMethod<[_jobId: BigNumberish], [string], "view">;
  getFunction(
    nameOrSignature: "getPauserCount"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "getQuantumStateInfo"
  ): TypedContractMethod<
    [_user: AddressLike],
    [
      [bigint, boolean, bigint] & {
        qubitCount: bigint;
        isEntangled: boolean;
        timestamp: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "getUserJobHistory"
  ): TypedContractMethod<[_user: AddressLike], [bigint[]], "view">;
  getFunction(
    nameOrSignature: "initializeQuantumState"
  ): TypedContractMethod<
    [_amplitudes: BigNumberish[], _qubitCount: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "isDecryptionAllowed"
  ): TypedContractMethod<[], [boolean], "view">;
  getFunction(
    nameOrSignature: "isSindCpadEnabled"
  ): TypedContractMethod<[], [boolean], "view">;
  getFunction(
    nameOrSignature: "jobDecryptionCallback"
  ): TypedContractMethod<
    [requestId: BigNumberish, decryptedValue: BigNumberish],
    [bigint],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "protocolId"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "quantumCircuits"
  ): TypedContractMethod<
    [arg0: BigNumberish],
    [[boolean, bigint] & { isCompiled: boolean; depth: bigint }],
    "view"
  >;
  getFunction(
    nameOrSignature: "requestJobDecryption"
  ): TypedContractMethod<[_jobId: BigNumberish], [bigint], "nonpayable">;
  getFunction(
    nameOrSignature: "revokeNodeAuthorization"
  ): TypedContractMethod<[_node: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "submitQuantumJob"
  ): TypedContractMethod<
    [_encryptedInput: BigNumberish, _algorithmType: BigNumberish],
    [bigint],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "updateMaxQubits"
  ): TypedContractMethod<[_newMax: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "userJobHistory"
  ): TypedContractMethod<
    [arg0: AddressLike, arg1: BigNumberish],
    [bigint],
    "view"
  >;
  getFunction(
    nameOrSignature: "verifyQuantumResult"
  ): TypedContractMethod<
    [_jobId: BigNumberish, _expectedResult: BigNumberish],
    [boolean],
    "nonpayable"
  >;

  getEvent(
    key: "CircuitCompiled"
  ): TypedContractEvent<
    CircuitCompiledEvent.InputTuple,
    CircuitCompiledEvent.OutputTuple,
    CircuitCompiledEvent.OutputObject
  >;
  getEvent(
    key: "EntanglementCreated"
  ): TypedContractEvent<
    EntanglementCreatedEvent.InputTuple,
    EntanglementCreatedEvent.OutputTuple,
    EntanglementCreatedEvent.OutputObject
  >;
  getEvent(
    key: "NodeAuthorized"
  ): TypedContractEvent<
    NodeAuthorizedEvent.InputTuple,
    NodeAuthorizedEvent.OutputTuple,
    NodeAuthorizedEvent.OutputObject
  >;
  getEvent(
    key: "QuantumJobCompleted"
  ): TypedContractEvent<
    QuantumJobCompletedEvent.InputTuple,
    QuantumJobCompletedEvent.OutputTuple,
    QuantumJobCompletedEvent.OutputObject
  >;
  getEvent(
    key: "QuantumJobSubmitted"
  ): TypedContractEvent<
    QuantumJobSubmittedEvent.InputTuple,
    QuantumJobSubmittedEvent.OutputTuple,
    QuantumJobSubmittedEvent.OutputObject
  >;
  getEvent(
    key: "QuantumResultDecrypted"
  ): TypedContractEvent<
    QuantumResultDecryptedEvent.InputTuple,
    QuantumResultDecryptedEvent.OutputTuple,
    QuantumResultDecryptedEvent.OutputObject
  >;
  getEvent(
    key: "QuantumStateInitialized"
  ): TypedContractEvent<
    QuantumStateInitializedEvent.InputTuple,
    QuantumStateInitializedEvent.OutputTuple,
    QuantumStateInitializedEvent.OutputObject
  >;

  filters: {
    "CircuitCompiled(uint256,uint256)": TypedContractEvent<
      CircuitCompiledEvent.InputTuple,
      CircuitCompiledEvent.OutputTuple,
      CircuitCompiledEvent.OutputObject
    >;
    CircuitCompiled: TypedContractEvent<
      CircuitCompiledEvent.InputTuple,
      CircuitCompiledEvent.OutputTuple,
      CircuitCompiledEvent.OutputObject
    >;

    "EntanglementCreated(address,address)": TypedContractEvent<
      EntanglementCreatedEvent.InputTuple,
      EntanglementCreatedEvent.OutputTuple,
      EntanglementCreatedEvent.OutputObject
    >;
    EntanglementCreated: TypedContractEvent<
      EntanglementCreatedEvent.InputTuple,
      EntanglementCreatedEvent.OutputTuple,
      EntanglementCreatedEvent.OutputObject
    >;

    "NodeAuthorized(address)": TypedContractEvent<
      NodeAuthorizedEvent.InputTuple,
      NodeAuthorizedEvent.OutputTuple,
      NodeAuthorizedEvent.OutputObject
    >;
    NodeAuthorized: TypedContractEvent<
      NodeAuthorizedEvent.InputTuple,
      NodeAuthorizedEvent.OutputTuple,
      NodeAuthorizedEvent.OutputObject
    >;

    "QuantumJobCompleted(uint256,address)": TypedContractEvent<
      QuantumJobCompletedEvent.InputTuple,
      QuantumJobCompletedEvent.OutputTuple,
      QuantumJobCompletedEvent.OutputObject
    >;
    QuantumJobCompleted: TypedContractEvent<
      QuantumJobCompletedEvent.InputTuple,
      QuantumJobCompletedEvent.OutputTuple,
      QuantumJobCompletedEvent.OutputObject
    >;

    "QuantumJobSubmitted(uint256,address,uint8)": TypedContractEvent<
      QuantumJobSubmittedEvent.InputTuple,
      QuantumJobSubmittedEvent.OutputTuple,
      QuantumJobSubmittedEvent.OutputObject
    >;
    QuantumJobSubmitted: TypedContractEvent<
      QuantumJobSubmittedEvent.InputTuple,
      QuantumJobSubmittedEvent.OutputTuple,
      QuantumJobSubmittedEvent.OutputObject
    >;

    "QuantumResultDecrypted(uint256,uint8)": TypedContractEvent<
      QuantumResultDecryptedEvent.InputTuple,
      QuantumResultDecryptedEvent.OutputTuple,
      QuantumResultDecryptedEvent.OutputObject
    >;
    QuantumResultDecrypted: TypedContractEvent<
      QuantumResultDecryptedEvent.InputTuple,
      QuantumResultDecryptedEvent.OutputTuple,
      QuantumResultDecryptedEvent.OutputObject
    >;

    "QuantumStateInitialized(address,uint8)": TypedContractEvent<
      QuantumStateInitializedEvent.InputTuple,
      QuantumStateInitializedEvent.OutputTuple,
      QuantumStateInitializedEvent.OutputObject
    >;
    QuantumStateInitialized: TypedContractEvent<
      QuantumStateInitializedEvent.InputTuple,
      QuantumStateInitializedEvent.OutputTuple,
      QuantumStateInitializedEvent.OutputObject
    >;
  };
}
